config/environments/production.rb

Signed off by: Rafael Reggiani Manzo <rr.manzo@gmail.com>

Changing configuration of Kalibro Client for production

---

spec/controllers/compound_metric_configurations_controller_spec.rb
spec/helpers/metric_configurations_helper_spec.rb

Signed off by: Rafael Manzo <rr.manzo@gmail.com>
Signed off by: Heitor Reis <marcheing@gmail.com>

Fixed compound metric test and added a test for supported_metrics_of

---

app/views/readings/_form.html.erb
db/schema.rb
features/reading/edit.feature
features/step_definitions/repository_steps.rb
features/step_definitions/user_steps.rb

Signed off by: Diego Araújo <diegoamc90@gmail.com>

Fixed color picker javascript

---

app/controllers/kalibro_ranges_controller.rb
features/kalibro_range/create.feature
features/kalibro_range/deletion.feature
features/kalibro_range/edit.feature
features/step_definitions/compound_metric_configuration_steps.rb
features/step_definitions/kalibro_range_steps.rb
spec/controllers/kalibro_ranges_controller_spec.rb

Acceptance tests for edit and delete pending
Signed off by: Diego Araújo <diegoamc90@gmail.com>

Changing the redirection path after create, edit or delete on a range

---

app/controllers/repositories_controller.rb
app/views/repositories/show.html.erb
config/routes.rb
spec/controllers/repositories_controller_spec.rb
spec/routing/repositories_routing_spec.rb

This should fix this issue at CodeClimate: https://codeclimate.com/github/mezuro/prezento/issues/categories/complexity

RepositoriesController#state splited into two simpler actions

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/concerns/ownership_authentication.rb
app/helpers/kalibro_configurations_helper.rb
app/views/layouts/application.html.erb
config/locales/views/en.yml
config/locales/views/pt.yml
config/routes.rb
features/compound_metric_configuration/create.feature
features/homepage.feature
features/step_definitions/compound_metric_configuration_steps.rb
features/step_definitions/kalibro_configuration_steps.rb
features/step_definitions/kalibro_range_steps.rb
features/step_definitions/metric_configuration_steps.rb
features/step_definitions/project_steps.rb
features/step_definitions/reading_group_steps.rb
features/step_definitions/reading_steps.rb
features/step_definitions/repository_steps.rb
spec/controllers/base_metric_configurations_controller_spec.rb
spec/controllers/compound_metric_configurations_controller_spec.rb
spec/controllers/home_controller_spec.rb
spec/controllers/kalibro_configurations_controller_spec.rb
spec/controllers/kalibro_ranges_controller_spec.rb
spec/controllers/metric_configurations_controller_spec.rb
spec/controllers/repositories_controller_spec.rb
spec/routing/home_routing_spec.rb
spec/routing/project_routing_spec.rb

This permits the language selection

Issue 03 auto lang

---

app/views/modules/_metric_results.html.erb
app/views/modules/_module_tree.html.erb
app/views/repositories/_form.html.erb
app/views/repositories/_metric_results_error.html.erb
app/views/repositories/_module_tree_error.html.erb
app/views/repositories/_processing_information.html.erb
app/views/repositories/_unstarted_processing.html.erb
app/views/repositories/edit.html.erb
app/views/repositories/new.html.erb
app/views/repositories/show.html.erb
config/locales/modules/en.yml
config/locales/modules/pt.yml
config/locales/views/processing/en.yml
config/locales/views/processing/pt.yml
config/locales/views/repository/en.yml
config/locales/views/repository/pt.yml
features/repository/show/date_select.feature
features/repository/show/repository_info.feature
features/step_definitions/repository_steps.rb

Date select feature not working on @rafamanzo's machine.

Translations for Repository

---

app/helpers/metric_configurations_helper.rb
features/metric_configuration/create.feature
spec/helpers/metric_configurations_helper_spec.rb

Signed-off-by: Álvaro Fernando <alvarofernandoms@hotmail.com>
Signed-off-by: Eduardo Brasil <brasil.eduardo1@gmail.com>

Added count option to the aggregation form on metrics configuration creation

---

app/views/repositories/_form.html.erb
config/locales/views/repository/en.yml
config/locales/views/repository/pt.yml

This is a MR for issue mezuro/prezento#214.
Updated periodicity translation on creating new repository page as well.
Signed-off-by: LucasLeite <lucas.srl08@gmail.com>

Fixing translations errors on creatint new repository

---

CHANGELOG.rdoc

New features and fixes should be added after the unreleased item.
On a release we put the version followed by the date in place of the Unreleased and create a new Unreleased.
It's partially based on GNU's format and Perl CPAN's one.

Added a CHANGELOG

---

app/controllers/application_controller.rb
spec/controllers/projects_controller_spec.rb

Generally rails will deal with this, but since we are already on a rescue
it will not handle to avoid an infinite loop. So we need to deal with the
error.

Page not found handler robust to unknown formats

---

app/views/projects/_form.html.erb

Signed-off-by: Pedro Scocco <pedroscocco@gmail.com>

Changed default value of project image

---

config/locales/views/layouts/en.yml
config/locales/views/layouts/pt.yml

Signed off by: Daniel Miranda <danielkza2@gmail.com>

Fixed missing mezuro team translation

---

db/seeds.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/reading_group_spec.rb

The script will make a request to the kalibro configurations server and
receive all the stored configurations, setting each one of them to
public, belonging to a default Mezuro User
Signed-off-by: Eduardo Silva <duduktamg@hotmail.com>

Added seeds script to set the default configurations to public

---

db/seeds.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/reading_group_spec.rb

Reverts mezuro/prezento#256
It is missing ReadinGroupAttributes.

Revert "Added seeds script to set the default configurations to public"

---

CHANGELOG.rdoc
Gemfile
Gemfile.lock
app/controllers/repositories_controller.rb
features/step_definitions/repository_steps.rb
spec/controllers/repositories_controller_spec.rb

Closes https://github.com/mezuro/prezento/issues/217

Kalibro client update

---

db/seeds.rb
spec/factories/users.rb

Signed-off-by: Pedro Scocco <pedroscocco@gmail.com>

Removed factory girl dependency from seeds

---

app/views/repositories/show.html.erb
features/repository/show/independent.feature
features/step_definitions/kalibro_configuration_steps.rb
features/step_definitions/repository_steps.rb

Fixes repository show page for independent repositories

---

app/views/compound_metric_configurations/_metric_options.html.erb

Signed off by: Heitor Reis <marcheing@gmail.com>

Retrieving metric code when updating a compound metric configuration

---

CHANGELOG.rdoc
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/module/graphic.js.coffee
app/assets/javascripts/module/tree.js.coffee
app/assets/javascripts/repository/branch.js.coffee
app/assets/javascripts/repository/state.js.coffee
config/initializers/jsroutes.rb
config/routes.rb
spec/javascripts/spec_helper.js.coffee

If set, RAILS_RELATIVE_URL_ROOT would break all the AJAX requests.

JS routes are now generated insted of being harcoded

---

Gemfile
Gemfile.lock
app/controllers/kalibro_ranges_controller.rb
app/helpers/kalibro_ranges_helper.rb
app/helpers/processings_helper.rb
app/views/metric_configurations/_ranges.html.erb
spec/helpers/kalibro_ranges_helper_spec.rb

There is a enhancement for the future: https://github.com/mezuro/kalibro_client/issues/73

Use kalibro client ranges

---

app/controllers/projects_controller.rb
app/models/project.rb
app/models/project_attributes.rb
app/views/modules/_module_tree.html.erb
config/deploy.rb
db/migrate/20151106182639_change_project_attributes_public_default.rb
db/schema.rb
features/project/deletion.feature
features/project/edition.feature
features/project/listing.feature
features/project/show.feature
features/repository/create.feature
features/repository/show/modules_tree.feature
features/step_definitions/project_steps.rb
spec/controllers/projects_controller_spec.rb
spec/factories/project_attributes.rb
spec/models/project_attributes_spec.rb
spec/models/project_spec.rb

Refers to the Bug Day of 2015/11/06

Bug busters

---

Gemfile

* This is needed for packaging on production environment

Put foreman gem in global scope on Gemfile

---

.travis.yml
app/controllers/repositories_controller.rb
config/routes.rb
features/repository/notify_push.feature
features/repository/show/hotspot_metric_results.feature
features/repository/show/metric_results.feature
features/step_definitions/compound_metric_configuration_steps.rb
features/step_definitions/repository_steps.rb
spec/controllers/repositories_controller_spec.rb
spec/factories/kalibro_configurations.rb
spec/factories/metric_configurations.rb
spec/routing/repositories_routing_spec.rb

Git lab hooks

---

config/environments/production.rb

This improves platform compatibility and reflects the new mezuro.org
configuration.

Defaults to localhost memcached server

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/base_metric_configurations_controller.rb
app/models/kalibro_configuration.rb
app/models/project.rb
app/models/reading_group.rb
db/migrate/20150225170704_create_project_attributes.rb
spec/controllers/metric_configurations_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/controllers/repositories_controller_spec.rb
spec/models/kalibro_configuration_spec.rb
spec/models/project_spec.rb
spec/models/reading_group_spec.rb

Integration of the new KalibroClient API, which uses Likeno now.

Kalibro client with likeno

---

app/helpers/compound_metric_configurations_helper.rb
config/locales/views/metric_configurations/en.yml
config/locales/views/metric_configurations/pt.yml
spec/helpers/compound_metric_configurations_helper_spec.rb

Signed-off-by: Eduardo Silva Araújo <duduktamg@hotmail.com>
Fixes #323.

Add FUNCTION scope to compound_metric_configuration form

---

app/views/compound_metric_configurations/_metric_options.html.erb
config/locales/views/compound_metric_configuration/en.yml
config/locales/views/compound_metric_configuration/pt.yml

Signed-off-by: Eduardo Silva Araújo <duduktamg@hotmail.com>
Fixes #324.

Fix missing Scope description in Compound Metric creation

---

app/views/compound_metric_configurations/_form.html.erb
app/views/kalibro_ranges/_form.html.erb
app/views/metric_configurations/_form.html.erb
app/views/repositories/_form.html.erb
app/views/tutorials/configuring.en.html.erb
app/views/tutorials/configuring.pt.html.erb

This removes one responsability from Prezento.
Signed-off-by: Rafael Reggiani Manzo <rr.manzo@protonmail.com>

Change tutorial's links to point to mezuro.github.io

---

CHANGELOG.rdoc
config/locales/views/metric_configurations/en.yml
config/locales/views/metric_configurations/pt.yml

Fixes #336.
Signed-off-by: otaviocv <otavio@deluqui.com.br>

Fix missing Compound Metric translation in choose_metric view

---

.travis.yml
CHANGELOG.md
bin/setup
config/environments/development.rb
config/environments/test.rb
config/kalibro.yml.sample
features/support/header.rb

Version with improved configuration compatibility for packaging.

Release version 1.1.0

---

CHANGELOG.md
app/helpers/repository_helper.rb
config/locales/default/en.yml
config/locales/default/pt.yml

Periods were not translated. Fixed.
Unit tests also created.

Fixing second part of the issue #312

---

CHANGELOG.md
app/models/concerns/has_owner.rb
app/models/kalibro_configuration.rb
app/models/project.rb
app/models/repository.rb

Refactored the method _self.latest_ to fix the duplicated code. To do it the code block was wrote to the has_owner concern

refactor latest method

---

README.md

This gives more visibility to what is getting done to interested users
and new developers.

Add waffle badge
