mezuro/prezento

Gemfile.lock, app/helpers/kalibro_modules_helper.rb, app/views/modules/_module_tree.html.erb, spec/factories/kalibro_modules.rb, spec/helpers/kalibro_module_helper_spec.rb
Greater granularities are listed on top of smaller ones. Equal granularities are ordered by their names.
Just like Nautilus sorts your files and folders.
This closes: https://github.com/mezuro/prezento/issues/90
=> Source tree sorted

app/views/devise/registrations/edit.html.erb, features/users/user_update.feature
Probably it got broken after the translations and the acceptance test was
passing due to the dependency of javascript.
The acceptance test was fixed and the form has now the right field type.
=> Fixes the user edition form

config/locales/devise/pt.yml, config/locales/views/devise/pt.yml
It was probably removed with the devise-i18n gem
Signed off by: Pedro Scocco <pedroscocco@gmail.com>
=> Add missing devise portuguese translation

app/models/project_attributes.rb, spec/models/project_attributes_spec.rb
It doesn't work since Project is an entity from KalibroClient, not a
normal ActiveRecord model.
=> Fix wrong association to Project in ProjectAttributes

app/assets/javascripts/module/graphic.js.coffee, app/assets/stylesheets/boilerplate/graphic.css, app/assets/stylesheets/module_results.css, app/views/modules/_metric_result.html.erb, app/views/modules/_metric_results.html.erb, app/views/modules/metric_history.js.erb
Fixed graphic for Metric Results not displaying correctly
The graphic for Metric results previously did not have a set size.
Changed it so that it fills the whole space available, and made it
responsive to window resizing. That broke some particular cases of
histories with few changes and number of points that wasn't very small.
In addition, made the graphic display a single point instead of an
unhelpful messa
=> Fixed and refactored graphic for Metric Results

app/controllers/repositories_controller.rb, spec/controllers/repositories_controller_spec.rb
Actions new and create check if project_id was provided before trying to check
the project ownership
=> RepositoriesController checks for Project ownership only if necessary

Gemfile, Gemfile.lock, config/initializers/konacha.rb
Use Thin when running Konacha tests, as recommended in
https://github.com/jfirebaugh/konacha/issues/146.
Hopefully it will make Travis stop exploding.
=> Attempt to fix Konacha test hangs on Travis by changing web server

app/views/repositories/show.html.erb
The button for searching for a processing result set by date manually
sets the HTML for the loading message. It was not using the correct
translation for the message. Fix that.
=> Fix missing translation on processing information when a date is chosen

Gemfile
Moved the gem dependency just for development and test environments.
=> sqlite3 is not necessary under production

app/helpers/kalibro_modules_helper.rb, spec/factories/kalibro_modules.rb, spec/helpers/kalibro_module_helper_spec.rb
The comparison is theoretically invalid. Still we want to do it in order to show it for the users.
Therefore, we define an order by overriding Granularity.
Signed off by: Rafael Reggiani Manzo <rr.manzo@gmail.com>
=> Fixes module tree ordering with FUNCTION granularity

app/controllers/concerns/ownership_authentication.rb, app/views/compound_metric_configurations/edit.html.erb, app/views/kalibro_ranges/edit.html.erb, app/views/metric_configurations/edit.html.erb, app/views/repositories/edit.html.erb, app/views/repositories/new.html.erb
Using URL helpers is not friendly with proxies like Colab. The path
helpers have the same effect unless we want sometime to render pages
outside Prezento context like embeds or sending emails.
Signed off by: Diego Araújo <diegoamc90@gmail.com>
=> Replace url route helpers by path ones

app/controllers/concerns/ownership_authentication.rb, app/controllers/kalibro_configurations_controller.rb, app/controllers/projects_controller.rb, app/controllers/reading_groups_controller.rb, spec/controllers/compound_metric_configurations_controller_spec.rb, spec/controllers/kalibro_configurations_controller_spec.rb, spec/controllers/kalibro_ranges_controller_spec.rb, spec/controllers/metric_configurations_controller_spec.rb, spec/controllers/projects_controller_spec.rb, spec/controllers/reading_groups_controller_spec.rb, spec/controllers/readings_controller_spec.rb, spec/controllers/repositories_controller_spec.rb
This is expected to improve compatibility with reverse-proxies.
Still, for full compatibility, regarding redirections, we still may
need to set the default url options with the proxy host.
Signed-off-by: Rafael Reggiani Manzo <rr.manzo@gmail.com>
=> Replace url helpers by the path ones

.travis.yml, app/helpers/metric_configurations_helper.rb, config/locales/views/metric_configurations/en.yml, config/locales/views/metric_configurations/pt.yml, features/golden_path/configure_and_process.feature, features/repository/show/metric_results.feature, features/step_definitions/repository_steps.rb, features/tree_metric_configuration/create.feature, spec/helpers/metric_configurations_helper_spec.rb
There were outdated tests that did not update from the deprecated
'Average' aggregation form to 'Mean'. Fix that, while simultaneously
refactoring the configuration creation and repository processing
features, into a single 'golden path' that tests boths, ensuring a very
common user task works as expected.
Signed-off-by: Daniel Miranda <danielkza2@gmail.com>
=> Aggregation form fix

app/controllers/repositories_controller.rb, features/repository/notify_push.feature, features/support/hooks.rb
Gitlab Webhooks didn't work since their service does not have a CSRF protection token to send on the request. Disable that protection for the `notify_push` action of the Repositories Controller.
=> Fix CSRF protection error in Gitlab webhooks

CHANGELOG.rdoc, app/views/kalibro_configurations/_metric_configurations.html.erb
This removes the `Show` button for hotspot metric configurations on the
configurations page.
Signed-off-by: Daniel Miranda <danielkza2@gmail.com>
Fixes #310.
=> Remove Show button for hotspot metric configurations

app/controllers/repositories_controller.rb, features/repository/notify_push.feature, features/step_definitions/repository_steps.rb, features/support/env.rb, features/support/header.rb, lib/webhooks.rb, lib/webhooks/base.rb, lib/webhooks/gitlab.rb, spec/controllers/repositories_controller_spec.rb, spec/factories/repositories.rb, spec/factories/webhooks.rb, spec/lib/webhooks/base_spec.rb, spec/lib/webhooks/gitlab_spec.rb
Ensure webhook requests are only accepted after proper verification of
expected headers, repository address and branch.
To that effect, split up the logic to extract that information from
requests to it's own class, and use it in the notify_push action.
Also, add factories to make better testing of the notify_push action
possible, such as a factory similar to a real request from Gitlab, and
one for the Kalibro Client repository on Gitlab.
Adding other hook providers should be quite a lot easier after this is
applied.
This fixes #326.
=> Refactor Webhook support to allow verification of parameters

CHANGELOG.rdoc, app/assets/stylesheets/bootstrap_and_overrides.css.less, app/controllers/home_controller.rb, app/models/kalibro_configuration.rb, app/models/repository.rb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, config/locales/views/home/en.yml, config/locales/views/home/pt.yml, config/locales/views/layouts/en.yml, config/locales/views/layouts/pt.yml, features/homepage.feature, features/step_definitions/homepage_steps.rb, features/users/user_update.feature, spec/controllers/home_controller_spec.rb, spec/models/kalibro_configuration_spec.rb, spec/models/repository_spec.rb
Information got update regarding PHP and copyright year.
The footer became a grid in order to better work on smaller screens.
=> Update home and remove menu

CHANGELOG.rdoc, app/views/kalibro_configurations/show.html.erb
Fixes view to use the correct translation keys that already existed.
Fixes #333.
Signed-off-by: Daniel Miranda <danielkza2@gmail.com>
=> Fix translations of "Tree Metrics" and "Hotspot Metrics"

CHANGELOG.rdoc, app/controllers/compound_metric_configurations_controller.rb, features/compound_metric_configuration/create.feature, features/step_definitions/compound_metric_configuration_steps.rb, features/support/env.rb, features/support/tables.rb, spec/controllers/compound_metric_configurations_controller_spec.rb
It makes it harder for an user to mistakenly add a metric to their
script that will never work.
Signed-off-by: Eduardo Araújo <duduktamg@hotmail.com>
Fixes #322.
=> Make Compound Metric Config. metric list not include Hotspot metrics

CHANGELOG.rdoc, app/views/repositories/show.html.erb, config/locales/views/repository/en.yml, config/locales/views/repository/pt.yml, features/repository/show/repository_info.feature, features/step_definitions/repository_steps.rb, features/support/env.rb, spec/controllers/repositories_controller_spec.rb
Expose, for the repository's owner, the url he/she can use for push notifications on gitlab webhooks.
Also includes coverage for a case `RepositoryController#notify_push` that was missing.
=> Expose notify push url

app/controllers/repositories_controller.rb, app/models/repository.rb, db/migrate/20160418192431_add_public_to_repository_attributes.rb, db/schema.rb, features/repository/index.feature, features/step_definitions/repository_steps.rb, spec/controllers/repositories_controller_spec.rb, spec/factories/repository_attributes.rb, spec/models/repository_spec.rb
This adds the functionality of hiding repositories that may be useful for not showing test repositories and the like.
This was needed since now repositories do not depend on projects to be created.
=> Hide repositories

CHANGELOG.rdoc, app/controllers/home_controller.rb, app/models/kalibro_configuration.rb, app/models/project.rb, app/views/home/index.html.erb, features/homepage.feature, features/step_definitions/kalibro_configuration_steps.rb, features/step_definitions/repository_steps.rb, spec/controllers/home_controller_spec.rb
There were instance variables filled by fetching the latest content
every time, defeating the purpose of the fragment caches in the view.
Replace them with helper methods, that also make the number of items
visible in the view.
Fixes #339.
Signed-off-by: otaviocv <otavio@deluqui.com.br>
=> Fix home page latest content cache efectiveness

.travis.yml, CHANGELOG.rdoc, features/support/header.rb, spec/rails_helper.rb
Include builds using ruby 2.0.0-p598 and 2.1.5, CentOS 7 and Debian 8 default versions respectively.
Remove unnecessary configurations.
Make Travis fail if unit test coverage is below 100%.
This closes https://github.com/mezuro/prezento/issues/351 and https://github.com/mezuro/prezento/issues/352
=> Update travis yml

.travis.yml, CHANGELOG.md, bin/setup, config/environments/development.rb, config/environments/test.rb, config/kalibro.yml.sample
This makes explicit that this is configurable and will be more packaging
friendly as the configuration file will get linked from /etc.
Signed-off-by: Eduardo Araújo <duduktamg@hotmail.com>
=> Load Kalibro service addresses from file

CHANGELOG.md, app/controllers/base_metric_configurations_controller.rb, app/controllers/kalibro_configurations_controller.rb, app/controllers/projects_controller.rb, app/controllers/reading_groups_controller.rb, app/controllers/readings_controller.rb, app/views/shared/_form_errors.html.erb
The change fixes deprecated warnings about "prezento_errors".
=> Changes 'kalibro_errors' to use 'likeno_errors'

bin/setup
Fix the problem of setup script trying to create the restart.txt without a tmp folder.
=> Create tmp folder on setup script

app/assets/stylesheets/footer.css, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
- Uses bootstrap container to enclose main content
- Adds dinamic stick footer. (mainly an enhancement for short pages)
=> Changes main content width (Closes #367)

app/models/concerns/has_owner.rb, app/models/kalibro_configuration.rb, app/models/project.rb, app/models/reading_group.rb, app/models/repository.rb
- Creates new concern call'd "HasOwner", that is usable in entities that belongs to users and can be private/public (for example: projects, repositories, and a few others)
- Refactor few classes to use the HasOwner concern - The classes are: "Project", "KalibroConfiguration", "ReadingGroup" and "Repository"
=> Refactor a few modules to use has_owner concern

CHANGELOG.md, app/models/kalibro_configuration_attributes.rb, app/models/project_attributes.rb, app/models/reading_group_attributes.rb, app/models/repository_attributes.rb, spec/models/kalibro_configuration_attributes_spec.rb, spec/models/project_attributes_spec.rb, spec/models/reading_group_attributes_spec.rb, spec/models/repository_attributes_spec.rb
=> Multiple attributes validates#244

Gemfile, app/controllers/application_controller.rb, public/406.html, spec/controllers/projects_controller_spec.rb
- Rescuing ActionView::MissingTemplate with `not_found` method located in `app/controllers/application_controller.rb`
- Modifying `not_found` method to render page telling that format given is unsupported
- Updating related tests
This PR closes #301
=> Handling unsupported format requests with error page

CHANGELOG.md, app/views/shared/_navbar.html.erb, config/locales/views/layouts/en.yml, config/locales/views/layouts/pt.yml, features/homepage.feature
It is redundant with the logo link.
=> Remove home link from navbar
